default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password:

development:
  <<: *default
  database: tl_development

test:
  <<: *default
  database: tl_test
